sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: chZ1gwKV7j/zLqhdJvkEMD81ispgPd8UGOrDekiJ3Jwb8g0o37h2VIhVYdy4TqbacdpbibMLSuMEbNvWJ80zPLbrLtKaZenUoGnKL4nZoLf3xpJ/rdEmkQxBrjmaHU60daNeH9zYx4V7DkHEtYqQgVFehc7qB2XyZShy9Z1VzlbPsJYhfzm0pDC7VrYeMp5gL+pJev/0IdNEpX2xH9kTHId4XX/I+No0FnfZt2RVEapykrQbhfZevfYvlwIRwVV5AueMrKPiRoakqN0au8TEmmMn/zYmLrPWkpmGeDnckmOHunUHWtUW3OVNz9OeXKp3z9DfEG/+IJ1fNQbIUCEvtcwaoN65rXs0sJkW2urzIYns1RGRC72hgJkSnOsChAxguSpS9nKZ+LDXdpL5N+TDPOCiYy41af0jA48OPbDiBvEuTfiEKtPymFY1xKNPf27hOgeXYAISA2ZwyJyDK57ViMQZJrFBMKWTLhA0PS1KW20ToetiEjcDJZ7rznJ5Clmpop75IzqWQ+Y4fGYgI9MclES0c97E7pF+qhYTdmRwXuGuCnMcR3rNe2+AmvFNN/rWMvPZ+V81lLPJ7JWVEo8nUslfOYqzHT8wFG99eayexVdacDwLKCQf784QjFlqZ50LJfTFT75OOKk4+zCU6ULbL2GZsQOs05OAs2OarVenW74=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Michel-and-Angele-A-Ladder-of-Swords-Volume-1_6250
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy